export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const CHANGE_TEMP_PARAM = 'CHANGE_TEMP_PARAM'
export const FETCH_BACKGROUND = 'FETCH_BACKGROUND'
export const SET_BACKGROUND = 'SET_BACKGROUND'
